# Generated by Django 5.2.4 on 2025-09-07 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_thread_message_userlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlink',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userlink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userlink',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlink',
            name='link_type',
            field=models.CharField(blank=True, choices=[('doctor_patient', 'Doctor ↔ Patient'), ('prothesist_patient', 'Prothesist ↔ Patient'), ('kinetherapist_patient', 'Kinetherapist ↔ Patient'), ('doctor_prothesist', 'Doctor ↔ Prothesist'), ('doctor_kinetherapist', 'Doctor ↔ Kinetherapist'), ('prothesist_kinetherapist', 'Prothesist ↔ Kinetherapist')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userlink',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='prothesist',
        ),
    ]
