# Generated by Django 5.2.4 on 2025-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userlink',
            unique_together={('from_user', 'to_user', 'link_type')},
        ),
    ]
