# Generated by Django 5.2.4 on 2025-10-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_dr_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reschedule_pending', 'Reschedule Pending')], default='pending', max_length=20),
        ),
    ]
